# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Fire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fire
   pod 'Firebase/Firestore'
   pod 'Firebase/Auth'
   pod 'Firebase/Storage'
   pod 'SDWebImage'
   pod 'ProgressHUD'

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
             config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
             config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
         end
     end
  end


end
